spring: 
  profiles:
    active:
    - dev
--- 
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-dept-dev
--- 
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-dept-test